{
    'name': 'Gestión de Licitaciones Públicas',
    'version': '19.0.2.0.0',
    'category': 'Sales/Public Procurement',
    'summary': 'Detección, criba y expedientes por empresa',
    'author': 'Alphaqueb Consulting SAS',
    'website': 'https://biotecgrupo.mx',
    'license': 'OPL-1',
    'icon': '/licitaciones_publicas/static/description/icon.svg',
    'depends': ['base', 'mail', 'web', 'contacts', 'report_xlsx'],
    'external_dependencies': {'python': ['openpyxl', 'xlsxwriter']},
    'data': [
        'security/licitaciones_security.xml', 'security/ir.model.access.csv',
        'data/sequences.xml', 'data/catalog_data.xml', 'data/tipos_archivo.xml',
        'reports/reports.xml', 'data/mail_templates.xml', 'data/cron.xml',
        'wizards/wizard_views.xml',
        'views/procedimiento_views.xml', 'views/partida_views.xml',
        'views/expediente_views.xml', 'views/carga_views.xml',
        'views/incidencia_views.xml', 'views/agenda_views.xml',
        'views/catalog_views.xml', 'views/settings_views.xml', 'views/menus.xml', 'views/tipo_archivo_views.xml',
    ],
    'demo': ['demo/demo_data.xml'],
    'assets': {'web.assets_backend': [
        'licitaciones_publicas/static/src/js/partida_empresas.js',
        'licitaciones_publicas/static/src/xml/partida_empresas.xml',
        'licitaciones_publicas/static/src/scss/licitaciones.scss',
    ]},
    'application': True,
    'installable': True,
}
