{
    'name': 'Gestión de Licitaciones Públicas',
    'version': '19.0.5.0.0',
    'category': 'Sales/Public Procurement',
    'summary': 'Centro de Licitaciones guiado: cargas, criba, renglones, expedientes y agenda con diseño propio',
    'author': 'Alphaqueb Consulting SAS',
    'website': 'https://biotecgrupo.mx',
    'license': 'OPL-1',
    'icon': '/licitaciones_publicas/static/description/icon.svg',
    'depends': ['base', 'mail', 'web', 'contacts', 'report_xlsx'],
    'external_dependencies': {'python': ['openpyxl', 'xlsxwriter', 'unidecode']},
    'data': [
        'security/licitaciones_security.xml', 'security/ir.model.access.csv',
        'data/sequences.xml', 'data/catalog_data.xml', 'data/tipos_archivo.xml',
        'reports/reports.xml', 'data/mail_templates.xml', 'data/cron.xml',
        'wizards/wizard_views.xml',
        'views/hub_views.xml',
        'views/procedimiento_views.xml', 'views/partida_views.xml',
        'views/expediente_views.xml', 'views/carga_views.xml',
        'views/incidencia_views.xml', 'views/agenda_views.xml',
        'views/catalog_views.xml', 'views/settings_views.xml', 'views/menus.xml', 'views/tipo_archivo_views.xml',
    ],
    'demo': ['demo/demo_data.xml'],
    'assets': {'web.assets_backend': [
        # sistema de diseño (el orden importa: variables y mixins primero)
        'licitaciones_publicas/static/src/scss/lp/_tokens.scss',
        'licitaciones_publicas/static/src/scss/lp/_hub.scss',
        'licitaciones_publicas/static/src/scss/lp/_native.scss',
        # widgets de las vistas nativas
        'licitaciones_publicas/static/src/js/partida_empresas.js',
        'licitaciones_publicas/static/src/xml/partida_empresas.xml',
        # Centro de Licitaciones (acción de cliente OWL)
        'licitaciones_publicas/static/src/js/lp/meta.js',
        'licitaciones_publicas/static/src/js/lp/data.js',
        'licitaciones_publicas/static/src/js/lp/nav.js',
        'licitaciones_publicas/static/src/js/lp/components.js',
        'licitaciones_publicas/static/src/js/lp/header.js',
        'licitaciones_publicas/static/src/js/lp/inicio.js',
        'licitaciones_publicas/static/src/js/lp/procedimientos.js',
        'licitaciones_publicas/static/src/js/lp/procedimiento.js',
        'licitaciones_publicas/static/src/js/lp/expedientes.js',
        'licitaciones_publicas/static/src/js/lp/expediente.js',
        'licitaciones_publicas/static/src/js/lp/carga.js',
        'licitaciones_publicas/static/src/js/lp/hub.js',
        'licitaciones_publicas/static/src/xml/lp_components.xml',
        'licitaciones_publicas/static/src/xml/lp_hub.xml',
        'licitaciones_publicas/static/src/xml/lp_inicio.xml',
        'licitaciones_publicas/static/src/xml/lp_procedimientos.xml',
        'licitaciones_publicas/static/src/xml/lp_procedimiento.xml',
        'licitaciones_publicas/static/src/xml/lp_expedientes.xml',
        'licitaciones_publicas/static/src/xml/lp_expediente.xml',
        'licitaciones_publicas/static/src/xml/lp_carga.xml',
    ]},
    'application': True,
    'installable': True,
}
