FROM odoo:19.0
USER root
COPY requirements.txt requirements-test.txt /tmp/licitaciones-ci/
RUN python3 -m pip install --no-cache-dir --break-system-packages \
    -r /tmp/licitaciones-ci/requirements-test.txt \
    && rm -rf /tmp/licitaciones-ci
USER odoo
